# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

{{- if eq .Values.whisk.ingress.type "standard" }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.whisk.ingress.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- range $key, $value := .Values.whisk.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if .Values.whisk.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.whisk.ingress.domain }}
    {{- if .Values.whisk.ingress.tls.secretenabled }}
    secretName: {{ .Values.whisk.ingress.tls.secretname | quote }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.whisk.ingress.domain }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx
          servicePort: http

{{- if .Values.whisk.ingress.tls.createsecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.whisk.ingress.tls.secretname | quote }}
  namespace: {{ .Release.Namespace | quote }}
type: {{ .Values.whisk.ingress.tls.secrettype | quote }}
data:
  tls.crt: {{ .Values.whisk.ingress.tls.crt }}
  tls.key: {{ .Values.whisk.ingress.tls.key }}
{{- end}}

{{- end }}
